apiVersion: v1
kind: ConfigMap
metadata:
  name: rss-hub-config
  labels:
    app.kubernetes.io/name: rss-hub
    app.kubernetes.io/component: app-config
data:
  SITE_URL: "https://rss-hub.pic-aichem.online"
  ALLOWED_HOSTS: "rss-hub.pic-aichem.online"
  CSRF_TRUSTED_ORIGINS: "https://rss-hub.pic-aichem.online"
  CSRF_COOKIE_SECURE: "1"
  SESSION_COOKIE_SECURE: "1"
  DATABASE_BACKEND: "postgres"
  POSTGRES_HOST: "rss-hub-postgres-rw"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "rsshub"
  POSTGRES_USER: "rsshub"
  ASYNC_TASK_BACKEND: "rq"
  ASYNC_QUEUE_NAME: "rsshub-default"
  ENABLE_CONTAINER_CRON: "0"
  WAIT_FOR_DB_ON_START: "1"
  WAIT_FOR_REDIS_ON_START: "1"
  RUN_COLLECTSTATIC_ON_START: "0"
  RUN_MAKEMIGRATIONS_ON_START: "0"
  RUN_MIGRATIONS_ON_START: "0"
  RUN_CREATE_SUPERUSER_ON_START: "0"
  RUN_COMPILEMESSAGES_ON_START: "0"
  DEFAULT_TARGET_LANGUAGE: "Chinese Simplified"
  TIME_ZONE: "Asia/Shanghai"
  LOG_LEVEL: "INFO"
  USER_MANAGEMENT: "0"
  DEMO: "0"
  DEBUG: "0"
