apiVersion: v1
kind: Secret
metadata:
  name: rss-hub-db-auth
  labels:
    app.kubernetes.io/name: rss-hub
    app.kubernetes.io/component: postgres
type: kubernetes.io/basic-auth
stringData:
  username: "rsshub"
  password: "replace-me"
