apiVersion: v1
kind: Secret
metadata:
  name: rss-hub-redis-auth
  labels:
    app.kubernetes.io/name: rss-hub
    app.kubernetes.io/component: redis
type: Opaque
stringData:
  password: "replace-me"
