apiVersion: v1
kind: Secret
metadata:
  name: rss-hub-app-secrets
  labels:
    app.kubernetes.io/name: rss-hub
    app.kubernetes.io/component: app-config
type: Opaque
stringData:
  SECRET_KEY: "replace-me"
  FIELD_ENCRYPTION_KEY: "replace-me"
  DEFAULT_SUPERUSER_USERNAME: "admin"
  DEFAULT_SUPERUSER_EMAIL: "admin@example.com"
  DEFAULT_SUPERUSER_PASSWORD: "replace-me"
