# Generated by Django 6.0.4 on 2026-04-17 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0038_source_kind_user_facing_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Archived'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='default_summarizer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workspaces_as_default_summarizer', to='core.openaiagent', verbose_name='Default Summarizer'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='default_translator_content_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workspace_default_translator', to='contenttypes.contenttype', verbose_name='Default Translator Type'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='default_translator_object_id',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Default Translator ID'),
        ),
    ]
