# Generated by Django 6.0.4 on 2026-04-18 06:30

import autoslug.fields
import core.models.workspace
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_feed_is_archived_workspace_default_summarizer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='source_kind',
            field=models.CharField(choices=[('translate', 'Translate'), ('github_md', 'GitHub Markdown')], default='translate', max_length=32, verbose_name='Source Kind'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='workspace',
            field=models.ForeignKey(default=core.models.workspace.get_default_workspace_id, on_delete=django.db.models.deletion.CASCADE, related_name='feeds', to='core.workspace', verbose_name='Workspace'),
        ),
        migrations.AlterField(
            model_name='feedgroup',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique_with=('workspace',), verbose_name='URL Slug'),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True, verbose_name='URL Slug'),
        ),
        migrations.CreateModel(
            name='WorkspaceMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('viewer', 'Viewer')], default='viewer', max_length=32, verbose_name='Role')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_memberships', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.workspace', verbose_name='Workspace')),
            ],
            options={
                'verbose_name': 'Workspace Membership',
                'verbose_name_plural': 'Workspace Memberships',
                'ordering': ['workspace__name', 'user__username'],
                'constraints': [models.UniqueConstraint(fields=('user', 'workspace'), name='unique_user_workspace_membership')],
            },
        ),
    ]
