"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import tomllib
from urllib.parse import parse_qsl, unquote, urlparse


# from django.utils.crypto import get_random_string
from django.core.management.utils import get_random_secret_key
import os
import sys

SITE_URL = os.environ.get("SITE_URL", "http://localhost:8000")
USER_MANAGEMENT = os.environ.get("USER_MANAGEMENT") == "1"
DEMO = os.environ.get("DEMO") == "1"
DATABASE_BACKEND = os.environ.get("DATABASE_BACKEND", "sqlite").lower()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# Read version from pyproject.toml
with open(BASE_DIR / "pyproject.toml", "rb") as f:
    pyproject = tomllib.load(f)
    VERSION = pyproject["project"]["version"]
LT_TIMEOUT=int(os.environ.get("LT_TIMEOUT", '5'))
SQLITE_TIMEOUT=float(os.environ.get("SQLITE_TIMEOUT", "30"))
OPENAI_API_TIMEOUT = float(os.environ.get("OPENAI_API_TIMEOUT", "120"))
OPENAI_API_MAX_RETRIES = max(0, int(os.environ.get("OPENAI_API_MAX_RETRIES", "0")))

X_FRAME_OPTIONS = os.environ.get("X_FRAME_OPTIONS", "DENY")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY", get_random_secret_key())
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG") == "1"

allowed_hosts_env = os.environ.get("ALLOWED_HOSTS")
if allowed_hosts_env:
    ALLOWED_HOSTS = [
        host.strip() for host in allowed_hosts_env.split(",") if host.strip()
    ]
else:
    ALLOWED_HOSTS = ["*"]
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get("CSRF_TRUSTED_ORIGINS", "http://*").split(",")
    if origin.strip()
]
INTERNAL_IPS = [
    "127.0.0.1",
]
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"

CSRF_COOKIE_SECURE = os.environ.get("CSRF_COOKIE_SECURE", "0") == "1"
SESSION_COOKIE_SECURE = os.environ.get("SESSION_COOKIE_SECURE", "0") == "1"
SESSION_COOKIE_DOMAIN = None
SESSION_COOKIE_AGE = 1209600  # 2 weeks
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_SAVE_EVERY_REQUEST = True
SESSION_ENGINE = "django.contrib.sessions.backends.db"
# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "core.apps.CoreConfig",
    "encrypted_model_fields",  # must set FIELD_ENCRYPTION_KEY value
    "tagulous",
]
DEBUG_PLUGINS = [
    "debug_toolbar",
    "bx_django_utils",  # https://github.com/boxine/bx_django_utils
]

SERIALIZATION_MODULES = {
    "xml": "tagulous.serializers.xml_serializer",
    "json": "tagulous.serializers.json",
    "python": "tagulous.serializers.python",
    "yaml": "tagulous.serializers.pyyaml",
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]
DEBUG_MIDDLEWARE = [
    "debug_toolbar.middleware.DebugToolbarMiddleware",
]
if DEBUG:
    INSTALLED_APPS += DEBUG_PLUGINS
    MIDDLEWARE += DEBUG_MIDDLEWARE


ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "core.context_processors.version",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
DATA_FOLDER = BASE_DIR / "data"
DATA_FOLDER.mkdir(exist_ok=True)
def _build_sqlite_database_config():
    return {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": DATA_FOLDER / "db.sqlite3",
        "OPTIONS": {
            "timeout": SQLITE_TIMEOUT,
        },
    }


def _build_postgres_database_config():
    database_url = os.environ.get("DATABASE_URL")
    if database_url:
        parsed = urlparse(database_url)
        if parsed.scheme not in {"postgres", "postgresql", "postgresql+psycopg"}:
            raise ValueError(f"Unsupported DATABASE_URL scheme: {parsed.scheme}")

        query_params = dict(parse_qsl(parsed.query, keep_blank_values=True))
        connect_timeout = int(
            query_params.pop(
                "connect_timeout", os.environ.get("POSTGRES_CONNECT_TIMEOUT", "5")
            )
        )
        conn_max_age = int(
            os.environ.get("POSTGRES_CONN_MAX_AGE", query_params.pop("conn_max_age", "60"))
        )

        return {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": unquote(parsed.path.lstrip("/"))
            or os.environ.get("POSTGRES_DB", "rsshub"),
            "USER": unquote(parsed.username or "")
            or os.environ.get("POSTGRES_USER", "rsshub"),
            "PASSWORD": unquote(parsed.password or "")
            or os.environ.get("POSTGRES_PASSWORD", ""),
            "HOST": parsed.hostname or os.environ.get("POSTGRES_HOST", "postgres"),
            "PORT": str(parsed.port or os.environ.get("POSTGRES_PORT", "5432")),
            "CONN_MAX_AGE": conn_max_age,
            "OPTIONS": {
                **query_params,
                "connect_timeout": connect_timeout,
            },
        }

    name = os.environ.get("POSTGRES_DB", "rsshub")
    user = os.environ.get("POSTGRES_USER", "rsshub")
    password = os.environ.get("POSTGRES_PASSWORD", "")
    host = os.environ.get("POSTGRES_HOST", "postgres")
    port = os.environ.get("POSTGRES_PORT", "5432")
    return {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": name,
        "USER": user,
        "PASSWORD": password,
        "HOST": host,
        "PORT": port,
        "CONN_MAX_AGE": int(os.environ.get("POSTGRES_CONN_MAX_AGE", "60")),
        "OPTIONS": {
            "connect_timeout": int(os.environ.get("POSTGRES_CONNECT_TIMEOUT", "5")),
        },
    }


if DATABASE_BACKEND == "postgres":
    DATABASES = {
        "default": _build_postgres_database_config(),
    }
else:
    DATABASES = {
        "default": _build_sqlite_database_config(),
    }

if not DEBUG and "test" not in sys.argv:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": os.getenv("REDIS_URL", "redis://localhost:6379/1"),
            "OPTIONS": {
                # Timeout for establishing a connection in seconds
                "socket_connect_timeout": 5,
                # Timeout for read/write operations in seconds
                "socket_timeout": 5,
                # Maximum number of connections in the pool
                "max_connections": 100,
            },
            # Default timeout for cache keys (1 day).
            # Keys without an expiration date will be cleaned up,
            # and expired keys are cleaned up periodically by Redis.
            "TIMEOUT": 60 * 60 * 24,
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        }
    }

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"
LANGUAGES = [
    ("zh-hans", "简体中文"),
    ("en-us", "English"),
]

LOCALE_PATHS = [BASE_DIR / "locale"]


TIME_ZONE = os.environ.get("TIME_ZONE", "UTC") # Asia/Shanghai,America/New_York,Europe/London

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "static"
STATICFILES_BACKEND = "whitenoise.storage.CompressedManifestStaticFilesStorage"
if "test" in sys.argv:
    STATICFILES_BACKEND = "django.contrib.staticfiles.storage.StaticFilesStorage"

STORAGES = {
    "staticfiles": {
        "BACKEND": STATICFILES_BACKEND,
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# https://pypi.org/project/django-encrypted-model-fields/
FIELD_ENCRYPTION_KEY = os.environ.get(
    "FIELD_ENCRYPTION_KEY", "RWdGiEq3LgOf3Tyt3ALlEnxUkIlL4wS2dCDBe_sLWWo="
)
ASYNC_TASK_BACKEND = os.environ.get("ASYNC_TASK_BACKEND", "local").lower()
ASYNC_QUEUE_NAME = os.environ.get("ASYNC_QUEUE_NAME", "rsshub-default")
ASYNC_REDIS_URL = os.environ.get(
    "ASYNC_REDIS_URL", os.environ.get("REDIS_URL", "redis://localhost:6379/1")
)
ENABLE_CONTAINER_CRON = os.environ.get("ENABLE_CONTAINER_CRON", "0") == "1"
DEFAULT_SUPERUSER_USERNAME = os.environ.get("DEFAULT_SUPERUSER_USERNAME", "admin")
DEFAULT_SUPERUSER_EMAIL = os.environ.get(
    "DEFAULT_SUPERUSER_EMAIL", "admin@example.com"
)
DEFAULT_SUPERUSER_PASSWORD = os.environ.get("DEFAULT_SUPERUSER_PASSWORD", "rssbox")

DEFAULT_TARGET_LANGUAGE = os.environ.get(
    "DEFAULT_TARGET_LANGUAGE", "Chinese Simplified"
)
TRANSLATION_LANGUAGES = [
    ("English", "English"),
    ("Chinese Simplified", "Chinese Simplified"),
    ("Chinese Traditional", "Chinese Traditional"),
    ("Russian", "Russian"),
    ("Japanese", "Japanese"),
    ("Korean", "Korean"),
    ("Czech", "Czech"),
    ("Danish", "Danish"),
    ("German", "German"),
    ("Spanish", "Spanish"),
    ("French", "French"),
    ("Indonesian", "Indonesian"),
    ("Italian", "Italian"),
    ("Hungarian", "Hungarian"),
    ("Norwegian Bokmal", "Norwegian Bokmal"),
    ("Dutch", "Dutch"),
    ("Polish", "Polish"),
    ("Portuguese", "Portuguese"),
    ("Swedish", "Swedish"),
    ("Turkish", "Turkish"),
]
LOG_LEVEL = os.environ.get(
    "LOG_LEVEL", "ERROR"
)  # DEBUG > INFO > WARNING > ERROR > CRITICAL
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            # "format": "{levelname} {asctime} {message:.500s}", 限制500字符
            "format": "{levelname} {asctime}<{name}>:{message}",
            "style": "{",
        },
    },
    "handlers": {
        "logfile": {
            "level": LOG_LEVEL,
            "class": "logging.handlers.RotatingFileHandler",
            "filename": DATA_FOLDER / "app.log",
            "maxBytes": 1024 * 1024 * 5,  # 10 MB
            "encoding": "utf-8",
            "backupCount": 2,
            "formatter": "verbose",
        },
        "console": {
            "level": LOG_LEVEL,
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["logfile", "console"],
        "level": LOG_LEVEL,
    },
}

default_title_translate_prompt = "You are a professional, authentic translation engine. Translate only the text into {target_language}, return only the translations, do not explain the original text."
default_content_translate_prompt = """
You are a professional, authentic translation engine specialized in HTML content translation. 

Requirements:
1. Translate only the text content into {target_language}
2. Preserve ALL HTML tags, attributes, and structure completely unchanged
3. Maintain proper context awareness across different HTML elements and their relationships
4. Consider semantic meaning within nested tags and their hierarchical context
5. Ensure translated text fits naturally within the HTML structure
6. Keep inline elements (like <span>, <a>, <strong>) contextually coherent with their surrounding text
7. Maintain consistency in terminology throughout the entire HTML document
8. Return only the translated HTML content without explanations or comments

Important: Do not modify, remove, or alter any HTML tags, attributes, classes, IDs, or structural elements. Only translate the actual text content between tags.

"""
default_summary_prompt = (
    "Summarize the following text in {target_language} and return markdown format."
)

default_digest_prompt = """
You are an editor-in-chief and expert analyst. Create a concise, objective, and well-structured daily digest from multiple articles.

OUTPUT FORMAT
3–5 categories (auto-generated, short topic names):
- Header: ## {category}
- Keep only the most important articles in this category
- For each kept article:
  - **[Title](LINK_X)**
  > 1–2 sentences, present tense, active voice; highlight novel results/decisions/metrics/impacts; avoid repeated phrasing.

Selection policy (apply strictly):
- Prioritize significance and real-world impact (e.g., regulatory decisions, major launches, security incidents, funding/M&A, peer-reviewed findings)
- Prioritize novelty; ignore incremental or routine updates and marketing/promotional posts
- Prefer credible, primary sources; avoid rumors/speculation
- Deduplicate across sources; if multiple items cover the same event, keep the most comprehensive one and drop the rest
- If a category has no important items, skip the category entirely

General rules:
- Maintain a neutral, objective tone; no content beyond the provided texts
- Extract facts, named entities, numbers, dates, and concrete outcomes
- Vary wording across items to avoid repetition
- Title rewrite (each item): rewrite into {target_language} objectively (no hype/clickbait/exclamations). Do NOT copy source wording; always paraphrase into a concise, neutral title even if the source is already in {target_language}.
"""

output_format_for_digest_prompt = """

**OUTPUT FORMAT**
- All headers, titles, and summaries must be in {target_language}.
- Return ONLY the digest content in the markdown format
- Use the exact LINK_X placeholders. Do not modify, replace, add, or remove links. Keep the format **[Title](LINK_X)**.
- Do NOT add any explanatory notes, disclaimers, or meta-commentary
- Do NOT provide usage instructions or suggestions
"""

default_filter_prompt = """
You are an advanced RSS content curator. Analyze the article following these protocols:

1. **Cross-article Deduplication**:
   - Identify duplicate content using semantic similarity
   - For duplicate sets:
     • Keep the most comprehensive version

2. **Ad Exclusion**:
   • Discard if any detected:
     - Promotional language patterns
     - Affiliate links
     - Brand mentions >5% of content
     - "Sponsored" disclosure

3. **Clickbait Detection**
   Discard if headline:
   - Uses sensational punctuation (e.g., "SHOCKING!", "You won't BELIEVE...")
   - Poses unanswered questions ("What happened next?")
   - Employs urgency/scarcity tactics ("Act NOW!")
"""

output_format_for_filter_prompt = """

**Output Requirements**
• Only return "Passed" or "Blocked" based on the above checks.
• ABSOLUTELY NO:
  - Explanations
  - Metadata
  - Discarded IDs
  - Additional text
"""
